Configure folders to dev

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,16 +1,36 @@
 #!/bin/bash
 
-SRC_FILE=$1
+SRC_FILE_PATH=$1
 
-if [ -z "$1" ]; then
-  echo "Usage: $0 <source_file>.c"
+if [ -z "$SRC_FILE_PATH" ]; then
+  echo "Usage: $0 <source_file_path>.c"
   exit 1
 fi
 
+if [ ! -f "$SRC_FILE_PATH" ]; then
+  echo "Not found $SRC_FILE_PATH"
+  exit 1
+fi
+
+SRC_PATH=`dirname $SRC_FILE_PATH`
+SRC_FILE=`basename $SRC_FILE_PATH`
+
+cd $SRC_PATH
+
+FILE_NAME=`echo $SRC_FILE | sed 's/\.c//g'`
+IHX_FILE=$FILE_NAME.ihx
+COM_FILE=$FILE_NAME.com
+
+rm -f $COM_FILE
+
 sdcc --code-loc 0x180 --data-loc 0 -mz80 --disable-warning 196 --no-std-crt0 $SDCC_LIB_Z80/crt0_msxdos_advanced.rel $SDCC_LIB_Z80/printf.rel $SDCC_LIB_Z80/putchar_msxdos.rel asm.lib fusion.lib $SRC_FILE
 
-IHX_FILE=`echo $SRC_FILE | sed 's/\.c//g'`.ihx
 
-hex2bin -e com $IHX_FILE
+if [ -f "$IHX_FILE" ]; then
+  hex2bin -e com $IHX_FILE
 
-rm *.lk *.lst *.map *.noi *.sym
+  mv $COM_FILE bin/
+fi
+
+rm -f $FILE_NAME.rel $FILE_NAME.asm
+rm -f *.ihx *.lk *.lst *.map *.noi *.sym
